print("Welcome to Valorant's gun shop")
x = int(input("Enter credit amount between 0 - 1000 "))
if x > 1000:
    print("That is an invalid amount of credits")
if x <= 1000:
    print("With that amount of credits, you are able to purchase")
    print("Price\tGun")
    print("Free\tClassic")
    print("300\tShorty")
    print("450\tFrenzy")
    print("500\tBandit")
    print("500\tGhost")
    print("800\tSheriff")
    print("1000\tStinger")
if x < 1000:
    print("With that amount of credits, you are able to purchase")
    print("Price\tGun")
    print("Free\tClassic")
    print("300\tShorty")
    print("450\tFrenzy")
    print("500\tBandit")
    print("500\tGhost")
    print("800\tSheriff")
if x < 800:
    print("With that amount of credits, you are able to purchase")
    print("Price\tGun")
    print("Free\tClassic")
    print("300\tShorty")
    print("450\tFrenzy")
    print("500\tBandit")
    print("500\tGhost")
